### ISSUE TITLE
Appmetrics-dash wont run in a docker(node:8-alpine) container

### ISSUE THREAD

**Issue by robin22d** [RuntimeTools/appmetrics-dash#139]
The app will run if ```node index.js``` is run but when run inside a docker container the error that i get is:

```
module.js:664
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /docker_node/node_modules/appmetrics/appmetrics.node)
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/docker_node/node_modules/appmetrics/index.js:23:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```
The Dockerfile: 

```
FROM node:8-alpine
COPY . /docker_node
WORKDIR /docker_node
RUN npm install
EXPOSE 9000
CMD [ "node", "index.js"]
```

The package.json:

```
{
  "name": "docker_node",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "appmetrics-dash": "^3.4.0",
    "express": "^4.16.3"
  },
  "devDependencies": {
    "assert": "^1.4.1",
    "http": "0.0.0"
  }
}

```

Server:

```
var express = require('express');
var dash = require('appmetrics-dash');
dash.attach();
var app = express();

app.get('/', function(req, res){
	res.send('Hello World');
});

app.get('/hello', function(req, res){
	res.send('Hello World...again!!');
});

app.listen(9000, function(){
	console.log('App listing on port 9000');
});

```

**Comment by stalleyj** [comment]
Unfortunately, Alpine linux is not a supported platform - see https://github.com/RuntimeTools/appmetrics
