### ISSUE TITLE
"Error: Can't set headers after they are sent" when using attach

### ISSUE THREAD

**Issue by sjanuary** [RuntimeTools/appmetrics-dash#151]
```
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at expressInit (/node_modules/express/lib/middleware/init.js:30:42)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/node_modules/express/lib/router/index.js:317:13)
    at /node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/node_modules/express/lib/router/index.js:335:12)
    at next (/node_modules/express/lib/router/index.js:275:10)
    at query (/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
Error: Can't render headers after they are sent to the client
    at ServerResponse.writeHead (_http_server.js:220:15)
    at XHR.Polling.onPollRequest (/node_modules/engine.io/lib/transports/polling.js:85:9)
    at XHR.Polling.onRequest (/node_modules/engine.io/lib/transports/polling.js:65:10)
    at XHR.onRequest (/node_modules/engine.io/lib/transports/polling-xhr.js:46:33)
    at /node_modules/engine.io/lib/server.js:230:46
    at Server.verify (/node_modules/engine.io/lib/server.js:171:3)
    at Server.handleRequest (/node_modules/engine.io/lib/server.js:222:8)
    at Server.<anonymous> (/node_modules/engine.io/lib/server.js:467:14)
    at Server.<anonymous> (/node_modules/socket.io/lib/index.js:343:16)
    at /node_modules/appmetrics-dash/lib/appmetrics-dash.js:197:16
```

**Comment by ddresch** [comment]
Any news on this one, any workarounds. Trying to connect node-red and I'm getting exact this error.

```
red.js -> before all require statements -> require('appmetrics-dash').attach();
```
