### ISSUE TITLE
Hapi

### ISSUE THREAD

**Issue by achingbrain** [RuntimeTools/appmetrics-dash#158]
Are there any instructions to get this module working with [Hapi](https://hapijs.com/)?  I can call the `attach` function and start my app as usual, but as soon as I open the dashboard in a web browser the monitored application crashes with the following stack trace:

```
_http_outgoing.js:491
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.writeHead (_http_server.js:215:21)
    at IncomingMessage.onEnd (/path/to/my/app/node_modules/engine.io/lib/transports/polling.js:180:9)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by achingbrain** [comment]
Actually I think I worked it out:

```javascript
const dash = require('appmetrics-dash')
const Hapi = require('hapi')

const server = new Hapi.Server({
  connections: {
    routes: {
      cors: true
    }
  }
)
server.connection({
  host: ...,
  port: ...,
  labels: 'myConnection'
})
server.connection({
  host: ...,
  port: ...,
  labels: 'myOtherConnection'
})

dash.monitor({
  server: server.select('myConnection').listener
})
dash.monitor({
  server: server.select('myOtherConnection').listener
})
```
