### ISSUE TITLE
error starting appmetrics-dash if no options are passed to the monitor() parameter

### ISSUE THREAD

**Issue by tobespc** [RuntimeTools/appmetrics-dash#17]
Passing empty options to dashboard fails

  require('appmetrics-dash').monitor();

C:\perf\acmeair-nodejs-master\node_modules\mongodb\lib\mongodb\mongo_client.js:475
          throw err
          ^
 AssertionError: false == true
    at Object.exports.monitor (C:\perf\acmeair-nodejs-master\node_modules\appmetrics-dash\lib\appmetrics-dash.js:117:5)
    at startServer (C:\perf\acmeair-nodejs-master\app-dash.js:184:32)
    at C:\perf\acmeair-nodejs-master\app-dash.js:175:2
    at C:\perf\acmeair-nodejs-master\dataaccess\mongo\index.js:132:15
    at C:\perf\acmeair-nodejs-master\node_modules\mongodb\lib\mongodb\mongo_client.js:472:11
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

C:\perf\acmeair-nodejs-master>npm install c:\work\git\appmetrics-dash

**Comment by tobespc** [comment]
this will be fixed by #18

**Comment by tobespc** [comment]
fixed by #18
