### ISSUE TITLE
Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by jiger25783** [RuntimeTools/appmetrics-dash#83]
Getting following issue
[06/13/17 10:07:05] com.ibm.diagnostics.healthcenter.mqtt INFO: Connected to broker localhost:1883
C:\workspace_trunk\xxxxx\node_modules\appmetrics-dash\node_modules\appmetrics\lib\aspect.js:55
                var existing = target[methodName];
                                     ^

TypeError: Cannot read property 'on' of undefined
    at C:\workspace_trunk\xxxxx\node_modules\appmetrics-dash\node_modules\appmetrics\lib\aspect.js:55:24
    at Array.forEach (native)
    at Object.exports.before (C:\workspace_trunk\xxxxx\node_modules\appmetrics-dash\node_modules\appmetrics\lib\aspect.js:54:8)
    at SocketioProbe.attach (C:\workspace_trunk\xxxxx\node_modules\appmetrics-dash\node_modules\appmetrics\probes\socketio-probe.js:68:10)
    at C:\workspace_trunk\xxxxx\node_modules\appmetrics-dash\node_modules\appmetrics\index.js:147:33

**Comment by jiger25783** [comment]
Tried with both 3.1.0 and 3.2.0

**Comment by sam-github** [comment]
Could you include the full stack trace? Also, what version(s) of socketio do you have installed? `npm ls socket.io` will tell you (actually, the entire `npm ls` dependency tree output would be useful).

**Comment by tobespc** [comment]
We have had this before https://github.com/RuntimeTools/appmetrics/issues/241

**Comment by sjanuary** [comment]
We had to close #241 as there wasn't enough information but it looks like we can now identify the probe that is causeing the issue which should help.
