### ISSUE TITLE
TypeError: Cannot read property '__appmetricsProbeAttached__' of null

### ISSUE THREAD

**Issue by mekterovic** [RuntimeTools/appmetrics-dash#85]
'm using node v7.2.1.

I've installed appmetrics-dash using: npm install appmetrics-dash

In the app, I've added a single line, after the express:

```
var express = require('express');
var dash = require('appmetrics-dash').monitor();
```

My app starts fine, I can see the dashboard at port 3001, but when I issue a query to the (PostgreSQL) database, appmetrics crashes, along with my application:
```
D:\Projekti\a2\app\edgar\node_modules\appmetrics-dash\node_modules\appmetrics\probes\postgres-probe.js:54
        if(!client.__appmetricsProbeAttached__) {
                  ^

TypeError: Cannot read property '__appmetricsProbeAttached__' of null
    at D:\Projekti\a2\app\edgar\node_modules\appmetrics-dash\node_modules\appmetrics\probes\postgres-probe.js:54:19
    at args.(anonymous function) (D:\Projekti\a2\app\edgar\node_modules\appmetrics-dash\node_modules\appmetrics\lib\aspect.js:26:4)
    at D:\Projekti\a2\app\edgar\node_modules\pg\lib\pool.js:81:27
    at D:\Projekti\a2\app\edgar\node_modules\generic-pool\lib\generic-pool.js:274:11
    at D:\Projekti\a2\app\edgar\node_modules\pg\lib\pool.js:30:28
    at Connection.<anonymous> (D:\Projekti\a2\app\edgar\node_modules\pg\lib\client.js:176:5)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Socket.<anonymous> (D:\Projekti\a2\app\edgar\node_modules\pg\lib\connection.js:59:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

FWIW, from the package.json:
```
    "pg": "^4.5.1",
    "pg-monitor": "^0.4.5",
    "pg-promise": "^3.2.6",
```

**Comment by mekterovic** [comment]
Sorry, guys, upgrading pg to the latest version fixed the issue, so I guess it is not appmetrics-dash issue after all, I'm closing this.

**Comment by vitaly-t** [comment]
if you include `pg-promise`, you do not need to include `pg` at all. And `pg-promise` is now v5.9.5, not the ancient 3.2.6
